name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Buildozer
        # Cambiamos a esta versión que es más estable para permisos
        uses: FarasAtmani/buildozer-action@v2
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}





